### ISSUE TITLE
Shopping Cart - Add, and remove buttons

### ISSUE THREAD

**Issue by CodeSaj** [CodeSaj/electronic-shop#6]
This will make the user shopping experience smoother, we need to add shopping symbols and make sure the user can add, remove or edit their order.

**Comment by ryant269** [comment]
Added shopping cart button. Need to make add/remove buttons for the items and shopping cart page to display the car items

**Comment by ryant269** [comment]
Updated shopping cart page. Need to make add/remove buttons
